# Generated by Django 5.1 on 2025-01-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Введите ФИО",
                        max_length=100,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "post",
                    models.CharField(
                        blank=True,
                        help_text="Введите должность",
                        max_length=100,
                        null=True,
                        verbose_name="Post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
    ]
